---

version: "3.7"

networks:
  koala:
    external: true

volumes:
  koala-mariadb-107:
    driver: local
  koala-postgres-11:
    driver: local
  koala-redis-7:
    driver: local
  koala-mysql-8:
    driver: local

services:

  traefik:
    image: traefik:v3.0
    container_name: koala-traefik
    networks:
      - koala
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--accessLog=true"
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.directory=/certs.conf.d/"
      - "--providers.file.watch=true"
    ports:
      - "${KOALA_HTTP_PORT}:80"
      - "${KOALA_HTTPS_PORT}:443"
      - "${KOALA_TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${KOALA_CERTIFICATES_PATH}/certs:/certs:ro"
      - "${KOALA_CERTIFICATES_PATH}/conf.d/:/certs.conf.d/:ro"

  mail:
    image: schickling/mailcatcher
    container_name: koala-mail
    networks:
      koala:
        aliases:
          - "mail.${KOALA_LOCAL_TLD}"
    labels:
      - "traefik.enable=true"

      # http => https redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.koala-mail-redirect.rule=Host(`mail.${KOALA_LOCAL_TLD}`)"
      - "traefik.http.routers.koala-mail-redirect.entrypoints=web"
      - "traefik.http.routers.koala-mail-redirect.middlewares=redirect-to-https"

      # https with ssl termination
      - "traefik.http.routers.koala-mail.rule=Host(`mail.${KOALA_LOCAL_TLD}`)"
      - "traefik.http.routers.koala-mail.entrypoints=websecure"
      - "traefik.http.routers.koala-mail.tls=true"
      - "traefik.http.routers.koala-mail.service=koala-mail"
      - "traefik.http.services.koala-mail.loadbalancer.server.port=1080"
    ports:
      - "1025:1025"
  mariadb107:
    image: "mariadb:10.7"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      koala:
        aliases:
          - mariadb107.services.docker
    volumes:
      - "koala-mariadb-107:/var/lib/mysql"
      - "./config/mariadb107/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf"
    ports:
      - "${KOALA_MARIADB107_PORT}:${KOALA_MARIADB107_PORT}"
  mysql8:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    networks:
      koala:
        aliases:
          - mysql8.services.docker
    volumes:
      - "koala-mysql-8:/var/lib/mysql"
      - "./config/mysql8/my.cnf:/etc/my.cnf"
    healthcheck:
      test: "/healthcheck.sh"
    ports:
      - "${KOALA_MYSQL8_PORT}:${KOALA_MYSQL8_PORT}"
  postgres11:
    image: "postgres:11-alpine"
    container_name: koala-postgres11
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
      PGPORT: "${KOALA_POSTGRES11_PORT}"
    networks:
      koala:
        aliases:
          - postgres11.services.docker
    volumes:
      - "koala-postgres-11:/var/lib/postgresql/data"
    ports:
      - "${KOALA_POSTGRES11_PORT}:${KOALA_POSTGRES11_PORT}"

  redis:
    image: "redis:7-alpine"
    container_name: koala-redis7
    networks:
      koala:
        aliases:
          - redis7.services.docker
    volumes:
      - "koala-redis-7:/data"
    expose:
      - "${KOALA_REDIS7_PORT}"
